# vector

In [2]:
import numpy as np

In [4]:
x = np.array([1,7,2],dtype=int) # 3 차원 벡터

In [6]:
y = np.array([5,2,1],dtype=int) # 3 차원 벡터

In [8]:
x+y

array([6, 9, 3])

In [9]:
x-y

array([-4,  5,  1])

In [10]:
x*y

array([ 5, 14,  2])

# 역행렬

### 행과 열의 개수가 같을 때

In [2]:
import numpy as np

In [3]:
x = np.array([[1,-2,3],[7,5,0],[-2,-1,2]])

In [4]:
np.linalg.inv(x)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [5]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

### 행과 열의 개수가 다를 때

In [8]:
Y = np.array([[0,1],[1,-1],[-2,1]])

In [9]:
np.linalg.pinv(Y)

array([[ 5.00000000e-01,  1.11022302e-16, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [11]:
np.linalg.pinv(Y) @ Y

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  1.00000000e+00]])